name: Standalone LineageOS Recovery Builder

on:
  workflow_dispatch:

jobs:
  build_recovery:
    runs-on: ubuntu-24.04
    permissions:
      contents: write

    steps:
    - name: Checkout Workflow Repository
      uses: actions/checkout@v4

    - name: Clean Runner Disk Space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Install Build Tooling Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32readline-dev lib32z1-dev libelf-dev liblz4-tool libsdl1.2-dev libssl-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python3 openjdk-17-jdk

    - name: Configure Repo Environment
      run: |
        mkdir -p ~/bin
        curl https://googleapis.com > ~/bin/repo
        chmod a+x ~/bin/repo
        echo "$HOME/bin" >> $GITHUB_PATH

    - name: Initialize Lineage Standalone Manifest
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"
        mkdir -p ~/android
        cd ~/android
        repo init -u https://github.com -b lineage-20.0 --depth=1

    - name: Shallow Sync (Recovery Minimal)
      run: |
        cd ~/android
        repo sync -c -j$(nproc --all) --force-sync --no-clone-bundle --no-tags

    - name: Clone Your Device Tree
      run: |
        cd ~/android
        git clone https://github.com -b X6525-user-13-TP1A.220624.014-646-release-keys device/infinix/Infinix-X6525

    - name: Build Standalone Recovery Image
      run: |
        cd ~/android
        source build/envsetup.sh
        export ALLOW_MISSING_DEPENDENCIES=true
        export BUILDING_RECOVERY_IMAGE=true
        lunch lineage_Infinix-X6525-userdebug
        mka recoveryimage -j$(nproc --all)

    - name: Upload Standalone recovery.img Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Standalone-Lineage-Recovery-X6525
        path: ~/android/out/target/product/Infinix-X6525/recovery.img
